//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.DANHGIA_DV = new HashSet<DANHGIA_DV>();
            this.HOADON_DV = new HashSet<HOADON_DV>();
            this.NHANVIEN_DV = new HashSet<NHANVIEN_DV>();
            this.SANPHAM_DV = new HashSet<SANPHAM_DV>();
        }
    
        public string MADV { get; set; }
        public string TENDV { get; set; }
        public string MOTA { get; set; }
        public string IMG { get; set; }
        public string IMG2 { get; set; }
        public string IMG3 { get; set; }
        public int GIA { get; set; }
        public double TONGDANHGIA { get; set; }
        public string IDDM { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA_DV> DANHGIA_DV { get; set; }
        public virtual DANHMUCDV DANHMUCDV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON_DV> HOADON_DV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN_DV> NHANVIEN_DV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM_DV> SANPHAM_DV { get; set; }
    }
}
