//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_SP
    {
        public int SOLUONG { get; set; }
        public int TONGTIEN { get; set; }
        public int GIA { get; set; }
        public int GIAMGIA { get; set; }
        public int THUE { get; set; }
        public string IDSP { get; set; }
        public string IDHOADON { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
