//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHEN
    {
        public string MADL { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<System.TimeSpan> THOIGIAN { get; set; }
        public bool TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
        public string TENKH { get; set; }
        public string EMAIL { get; set; }
        public string SODTKH { get; set; }
        public string IDKHACHHANG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
