//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KHOCTHATNHIEUDB1 : DbContext
    {
        public KHOCTHATNHIEUDB1()
            : base("name=KHOCTHATNHIEUDB1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DANHGIA_DV> DANHGIA_DV { get; set; }
        public virtual DbSet<DANHGIA_NV> DANHGIA_NV { get; set; }
        public virtual DbSet<DANHMUCDV> DANHMUCDVs { get; set; }
        public virtual DbSet<DANHMUCSP> DANHMUCSPs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HOADON_DV> HOADON_DV { get; set; }
        public virtual DbSet<HOADON_SP> HOADON_SP { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LICHHEN> LICHHENs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHANVIEN_DV> NHANVIEN_DV { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<SANPHAM_DV> SANPHAM_DV { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<DANHGIA_SP> DANHGIA_SP { get; set; }
    }
}
