//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.HOADON_SP = new HashSet<HOADON_SP>();
            this.DANHGIA_SP = new HashSet<DANHGIA_SP>();
            this.SANPHAM_DV = new HashSet<SANPHAM_DV>();
        }
    
        public string IDSP { get; set; }
        public string TENSP { get; set; }
        public string MOTA { get; set; }
        public string IMG { get; set; }
        public string IMG2 { get; set; }
        public string IMG3 { get; set; }
        public int GIA { get; set; }
        public double TONGDANHGIA { get; set; }
        public int THUE { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
        public string IDDM { get; set; }
        public string DONVITINH { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual DANHMUCSP DANHMUCSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON_SP> HOADON_SP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA_SP> DANHGIA_SP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM_DV> SANPHAM_DV { get; set; }
    }
}
