//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM_DV
    {
        public string MADV { get; set; }
        public string TENDV { get; set; }
        public string IDSP { get; set; }
        public string TENSP { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
